projectRoot = "../.."

compiler = "clang++"
ar = "ar"
compilerFrontend="gcc"

flags = [
    "-std=c++20",
    "-O3",
    "-g",
    "-fsanitize=address",
    "-fno-omit-frame-pointer", # get nicer stack traces from address sanitizer.
    "-fsanitize=undefined",
    "-Wall"
]

[[builds]]
    name = "easing"
    buildRule = "dynamiclib"
    outputName = "Easing"
    srcDirs = ["lib"]
    includePaths = ["include", "deps/CppEssentials/include"]


[[builds]]
    name = "tests"
    requires = ["easing"]
    buildRule = "exe"
    outputName = "Tests"
    srcDirs = ["tests"]
    includePaths = ["include", "deps/CppEssentials/include"]

