projectRoot = "../.."

compiler = "clang++"
ar = "ar"
compilerFrontend="gcc"

flags = [
    "-std=c++20",
    "-O3",
    "-g",
    "-fsanitize=address",
    "-fno-omit-frame-pointer", # get nicer stack traces from address sanitizer.
    "-fsanitize=undefined",
    "-Wall"
]

[[builds]]
    name = "essentials"
    buildRule = "dynamiclib"
    outputName = "Essentials"
    srcDirs = ["deps/CppEssentials/lib"]
    localIncludePaths = ["deps/CppEssentials/include"]

[[builds]]
    name = "easing"
    requires = ["essentials"]
    buildRule = "dynamiclib"
    outputName = "Easing"
    srcDirs = ["lib"]
    localIncludePaths = ["include"]


[[builds]]
    name = "tests"
    requires = ["essentials", "easing"]
    buildRule = "exe"
    outputName = "Tests"
    srcDirs = ["tests"]
    localIncludePaths = ["include"]

